spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: ${VIDEO_SERVICE_GENERAL_KEY_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_GENERAL_KEY_NAME}:${KEYCLOAK_PORT}/realms/sample-project-realm
  data:
    mongodb:
      host: ${MONGODB_GENERAL_KEY_NAME}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_GENERAL_KEY_NAME}:${KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: ${VIDEO_SERVICE_PORT}
  servlet:
    context-path: /${VIDEO_SERVICE_CONTEXT_PATH}