spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: ${VIDEO_SERVICE_GENERAL_KEY_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_GENERAL_KEY_NAME}:${KEYCLOAK_PORT}/realms/sample-project-realm
server:
  port: ${VIDEO_SERVICE_PORT}
  servlet:
    context-path: /${VIDEO_SERVICE_CONTEXT_PATH}